package com.example.demo.infrastructure.mapper;

import com.example.demo.domain.model.Tasks;
import com.example.demo.domain.model.TasksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TasksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    long countByExample(TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    int deleteByExample(TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    int insert(Tasks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    int insertSelective(Tasks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    List<Tasks> selectByExample(TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    Tasks selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    int updateByExampleSelective(@Param("row") Tasks row, @Param("example") TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    int updateByExample(@Param("row") Tasks row, @Param("example") TasksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    int updateByPrimaryKeySelective(Tasks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TASKS
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    int updateByPrimaryKey(Tasks row);
}