package com.example.demo.domain.model;

import java.util.Date;

public class Tasks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.ID
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.TITLE
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.DESCRIPTION
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.IS_COMPLETED
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    private Boolean isCompleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.DUE_DATE
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    private Date dueDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.ID
     *
     * @return the value of TASKS.ID
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.ID
     *
     * @param id the value for TASKS.ID
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.TITLE
     *
     * @return the value of TASKS.TITLE
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.TITLE
     *
     * @param title the value for TASKS.TITLE
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.DESCRIPTION
     *
     * @return the value of TASKS.DESCRIPTION
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.DESCRIPTION
     *
     * @param description the value for TASKS.DESCRIPTION
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.IS_COMPLETED
     *
     * @return the value of TASKS.IS_COMPLETED
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    public Boolean getIsCompleted() {
        return isCompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.IS_COMPLETED
     *
     * @param isCompleted the value for TASKS.IS_COMPLETED
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    public void setIsCompleted(Boolean isCompleted) {
        this.isCompleted = isCompleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.DUE_DATE
     *
     * @return the value of TASKS.DUE_DATE
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.DUE_DATE
     *
     * @param dueDate the value for TASKS.DUE_DATE
     *
     * @mbg.generated Fri Jul 04 13:47:21 JST 2025
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
}