DROP TABLE IF EXISTS tasks;

CREATE TABLE tasks (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION TEXT,
    IS_COMPLETED BOOLEAN DEFAULT FALSE NOT NULL,
    DUE_DATE TIMESTAMP NOT NULL
);